public enum Accessories {
    SPORTS_SEATS,
    WINDOW_TINT,
    HEATED_SEATS,
    HIGH_END_SOUND,
    TRUNK_ORGANIZER,
    BACK_UP_CAMERA,
    FLOOR_MATS,
    BLUE_TOOTH,
    EXTRA_CUP_HOLDERS,
    PHONE_CHARGER
}
